{{- if and .Values.envoy.enabled .Values.envoy.telemetry.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "telemetry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  bearer-token: {{ .Values.envoy.telemetry.bearerToken | b64enc }}
{{- end }}
