{{- if .Values.openwebui.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "initjob.fullname" . }}"
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 6
  template:
    metadata:
      name: "{{ include "initjob.fullname" . }}"
      labels:
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: Never
      initContainers:
        - name: check-openwebui
          image: alpine/curl:latest
          command: ["sh", "-c", "until curl -f 'http://{{ include "openwebui.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:8080/health'; do echo waiting for openwebui; sleep 2; done"]
      containers:
        - name: init
          image: {{ .Values.initJob.image.repository }}:{{ .Values.initJob.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: {{ .Values.initJob.image.pullPolicy }}
          args: ["init"]
          env:
            - name: INIT_OPEN_WEBUI__ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "initjob.fullname" . }}
                  key: OPENWEBUI_ADMIN_PASSWORD
            - name: CONFIG_PATH
              value: /svc/config.toml
          resources:
            requests:
              cpu: 0.5
              memory: 1Gi
            limits:
              cpu: 1
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /svc/config.toml
              subPath: config.toml
  {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
  {{- end }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "initjob.fullname" . }}
{{- end }}
