{{- if .Values.openwebui.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "initjob.fullname" . }}
type: Opaque
stringData:
  config.toml: |
    [open_webui]
    host = "{{ include "openwebui.fullname" . }}.{{ $.Release.Namespace }}.svc.cluster.local:8080"
    admin_user = "{{ .Values.openwebui.admin.user | required ".Values.openwebui.admin.user is required" }}"
    admin_email = "{{ .Values.openwebui.admin.email | required ".Values.openwebui.admin.email is required"}}"
    model_ids = [{{ range $name, $model := .Values.models }}"{{ $model.fullName }}",{{ end }}]
  OPENWEBUI_ADMIN_PASSWORD: {{ .Values.openwebui.admin.password | required ".Values.openwebui.admin.password" | quote }}
{{- end }}
