{{- if and .Values.openwebui.enabled  .Values.openwebui.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-openwebui-data
  labels:
    app: openwebui
    release: {{ .Release.Name }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - {{ .Values.openwebui.persistence.accessMode | default "ReadWriteOnce" }}
  storageClassName: {{ .Values.openwebui.persistence.storageClass | default "default" }}
  resources:
    requests:
      storage: {{ .Values.openwebui.persistence.size | default "10Gi" }}
{{- end }}
