{{- range $name, $model := .Values.models }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "model.fullname" (merge (dict "modelName" $name) $) }}"
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  apiKey: {{ $model.apiKey| required "apiKey must be set on model" | b64enc | quote }}
{{- end }}
