apiVersion: v1
kind: Secret
metadata:
  name: "postgres-secret"
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword | required ".Values.postgresql.auth.postgresPassword is required" }}
  OPENWEBUI_PG_PASSWORD: {{ .Values.openwebui.postgres.password | required ".Values.openwebui.postgres.password is required" }}
  OPENWEBUI_DATABASE_URL: "postgresql://openwebui:{{.Values.openwebui.postgres.password | required ".Values.openwebui.postgres.password is required"}}@{{ .Release.Name }}-postgresql:5432/openwebui"
  AUTHENTIK_PG_PASSWORD: {{ .Values.authentik.authentik.postgresql.password | required ".Values.authentik.postgresql.password is required" }}
