apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-initdb-scripts
data:
  init-users.sql: |
    CREATE USER openwebui WITH PASSWORD '{{ .Values.openwebui.postgres.password}}';
    CREATE DATABASE openwebui WITH OWNER openwebui;
    GRANT ALL PRIVILEGES ON DATABASE "openwebui" TO openwebui;
    GRANT ALL PRIVILEGES ON SCHEMA "public" TO openwebui;


    CREATE USER authentik WITH PASSWORD '{{ .Values.authentik.authentik.postgresql.password }}';
    CREATE DATABASE authentik WITH OWNER authentik;
    GRANT ALL PRIVILEGES ON DATABASE "authentik" TO authentik;
    GRANT ALL PRIVILEGES ON SCHEMA "public" TO authentik;
