apiVersion: v1
kind: Secret
metadata:
  name: postgres-initdb-secret
type: Opaque
stringData:
  OPENWEBUI_PG_PASSWORD: {{ .Values.openwebui.postgres.password | required ".Values.openwebui.postgres.password is required" }}
  AUTHENTIK_PG_PASSWORD: {{ .Values.authentik.authentik.postgresql.password | required ".Values.authentik.postgresql.password is required" }}
