{{- if .Values.envoy.enabled }}
  {{- range $name, $model := .Values.models }}
    {{- $fullname := include "model.fullname" (merge (dict "modelName" $name) $) }}
    {{- if or $model.internal (and (not $model.internal) $model.apiUrl) }}
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: AIServiceBackend
metadata:
  name: {{ $fullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: model-{{ $name }}
    release: {{ $.Release.Name }}
spec:
  schema:
    name: OpenAI
    version: "v1"
  backendRef:
    name: {{ $fullname }}
    kind: Backend
    group: gateway.envoyproxy.io
    {{- end }}
  {{- end }}
{{- end }}
