{{- if .Values.envoy.enabled }}
  {{- range $name, $model := .Values.models }}
    {{- $fullname := include "model.fullname" (merge (dict "modelName" $name) $) }}
    {{- if or $model.internal (and (not $model.internal) $model.apiUrl) }}
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: {{ $fullname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: model-{{ $name }}
    release: {{ $.Release.Name }}
spec:
  endpoints:
      {{- if $model.internal }}
    - fqdn:
        hostname: {{ $fullname }}.{{ $.Release.Namespace }}.svc.cluster.local
        port: 80
      {{- else if $model.apiUrl }}
    - fqdn:
        hostname: {{ $model.apiUrl | replace "https://" "" | replace "http://" "" }}
        port: 443
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
