{{- if .Values.envoy.enabled }}
  {{- range $name, $model := .Values.models }}
    {{- $fullname := include "model.fullname" (merge (dict "modelName" $name) $) }}
    {{- if or $model.internal (and (not $model.internal) $model.apiUrl) }}
---
apiVersion: aigateway.envoyproxy.io/v1alpha1
kind: BackendSecurityPolicy
metadata:
  name: {{ $fullname }}-security
  namespace: {{ $.Release.Namespace }}
  labels:
    app: model-{{ $name }}
    release: {{ $.Release.Name }}
spec:
  type: APIKey
  targetRefs:
    - group: aigateway.envoyproxy.io
      kind: AIServiceBackend
      name: {{ $fullname }}
  apiKey:
    secretRef:
      name: {{ $fullname }}
    {{- end }}
  {{- end }}
{{- end }}
