name: RunAI Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq age

      - name: Setup SOPS
        uses: nhedger/setup-sops@v2
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

      - name: Authenticate with RunAI
        env:
          RUNAI_CLIENT_ID: ${{ secrets.RUNAI_CLIENT_ID }}
          RUNAI_CLIENT_SECRET: ${{ secrets.RUNAI_CLIENT_SECRET }}
        run: |
          echo "Getting Access Token..."
          TOKEN_RESPONSE=$(curl -s -X POST https://sdsc.run.ai/api/v1/token \
            --header 'Accept: */*' \
            --header 'Content-Type: application/json' \
            --data-raw "{\"grantType\":\"client_credentials\", \"clientId\": \"$RUNAI_CLIENT_ID\", \"clientSecret\": \"$RUNAI_CLIENT_SECRET\"}")

          ACCESS_TOKEN=$(echo "$TOKEN_RESPONSE" | jq -r '.accessToken')
          echo "ACCESS_TOKEN=$ACCESS_TOKEN" >> $GITHUB_ENV

      - name: Install RunAI CLI
        run: |
          echo "Installing RunAI CLI..."
          curl -s https://sdsc.run.ai/api/v1/cli-exposer/installer/unix --header "Authorization: Bearer ${{ env.ACCESS_TOKEN }}" | bash
          echo "$HOME/.runai/bin" >> $GITHUB_PATH

      - name: Login to RunAI
        env:
          RUNAI_CLIENT_ID: ${{ secrets.RUNAI_CLIENT_ID }}
          RUNAI_CLIENT_SECRET: ${{ secrets.RUNAI_CLIENT_SECRET }}
        run: |
          echo "Logging into RunAI..."
          runai login access-key --client-id=$RUNAI_CLIENT_ID --secret=$RUNAI_CLIENT_SECRET --interactive=disabled --save

      - name: Set Kubeconfig
        run: |
          echo "Setting Kubeconfig..."
          mkdir -p $HOME/.kube
          cp scripts/kube.config $HOME/.kube/config
          export KUBECONFIG=$HOME/.kube/config
          runai kc set --bypass-validation

      - name: Decrypt Helm values
        env:
          SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
        run: |
          echo "Decrypting Helm values..."
          sops --decrypt --in-place values.sharedllm.yaml

      - name: Deploy with Helm
        run: |
          echo "Deploying application with Helm..."
          helm upgrade --install --force-conflicts sharedllm . --namespace runai-sharedllm-ralf -f values.sharedllm.yaml
